### ISSUE TITLE
To open Corona Warn App link on checkout from Meine Checkins WebView

### ISSUE THREAD

**Issue by stringparser** [railslove/rcvr-app#225]
Hi there. 

I'm trying to figure out if is possible to open universal links from meine checkins WebView i.e. Corona Warn App. Currently these links doesn't open in the CWA app but on a new tab on the WebView (asking you to install the app). The ideal would be that on the WebView of meine checkins the link opened just like it does on the browser but somehow it doesn't so I'm looking to why that could be.

For what I can see here

https://github.com/railslove/rcvr-app/blob/f6261435510fd0066749e04bf19141348c534507/lib/cwa/generateCwaLink.ts#L38-L69

in recover is open with `window.open` so I was wondering if because of this reason. 

Do you think the universal link would work if we had an `a` tag with an `href`? I'm not sure if that's possible to do on recover for privacy reasons but... if is possible to have an `a` + `href` would also make it work from the app by preventing default an opening the link `href` from there.

If you happen to have a link for testing this first I can see if this would work on the context of webview on meine checkins. Maybe just need an `a` + `href`.

**Comment by rennrennrenn** [comment]
@stringparser 
Take a look #228 this seems to work.
Maybe we can close the issue then?

**Comment by stringparser** [comment]
Ah nice! Thanks @rennrennrenn ;) Let me check that quickly and I'll close this. Should work I think.

**Comment by salimhb** [comment]
Yes, tested it and can confirm that it's working.

**Comment by salimhb** [comment]
It would be nice if someone with and Android device could confirm this too!

**Comment by stringparser** [comment]
@salimhb just tested with `iOS` let me confirm with `android` too ;)

**Comment by stringparser** [comment]
Using this QR for testing: 

![image](https://user-images.githubusercontent.com/7457705/121646181-55999b00-ca95-11eb-9ad2-7eeda413f979.png)

Yes it does work on `android` too! 💪 

Well done @rennrennrenn !
